version: "2"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redis
  staticfiles:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
  reverseproxy:
    build:
      dockerfile: reverse.Dockerfile
    ports:
      - "8080:80"
